src/config/urls.py
from django.contrib import admin
from django.urls import path

from main.views import IndexView, PageNotFondView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path("admin/", admin.site.urls),  # admin site
    path("__debug__/", include("debug_toolbar.urls")),
    path("", IndexView.as_view(), name="index"),
    path("main/", include("main.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
handler404 = PageNotFondView.as_view()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path

from groups.views import (
    GroupTeacherListView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
    TeacherGroupListView,
    GetGroupView,
)

app_name = "groups"

urlpatterns = [
    path("", GetGroupView.as_view(), name="get_group"),
    path("group_teacher_list_view<int:pk>/", GroupTeacherListView.as_view(), name="group_teacher_list_view"),
    path("teacher_group_list/<int:pk>/", TeacherGroupListView.as_view(), name="teacher_group_list_view"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

src/main/urls.py
from django.urls import path

from main.views import (
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    GuestView,
    UserActivateView,
    ProfileView,
    UpdateUserView,
)

app_name = "main"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("guest/", GuestView.as_view(), name="guest"),
    path("activate_user/<str:uuid64>/<str:token>/", UserActivateView.as_view(), name="activate_user"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("update_user/<int:pk>/", UpdateUserView.as_view(), name="update_user"),
]

src/groups/models.py
import random

from django.db import models
from faker import Faker


class Group(models.Model):
    groups_name = models.CharField(max_length=120, null=True, blank=True)
    direction = models.CharField(max_length=120, null=True, blank=True)
    location_school = models.CharField(max_length=100, null=True, blank=True)
    price = models.PositiveSmallIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "Groups"
        verbose_name_plural = "All groups"
        ordering = ("groups_name",)

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        direction_list = [
            "Programming",
            "Testing",
            "Management",
            "Marketing",
            "Design",
            "Сourses for schoolchildren",
        ]
        for _ in range(count):
            cls.objects.create(
                groups_name=faker.word(),
                direction=random.choice(direction_list),
                location_school=faker.address(),
                price=random.randint(10000, 30000),
            )

    def __str__(self):
        return f"{self.groups_name}".upper()

src/groups/forms.py
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = [
            "groups_name",
            "direction",
            "location_school",
            "price",
        ]

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404

from groups.forms import GroupForm
from groups.models import Group
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView

from teachers.models import Teacher


class GetGroupView(LoginRequiredMixin, ListView):
    model = Group
    template_name = "group_get.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_group")
    context_object_name = "groups"
    queryset = Group.objects.all()
    login_url = "main:guest"


class CreateGroupView(LoginRequiredMixin, CreateView):
    template_name = "student-create.html"
    form_class = GroupForm
    success_url = reverse_lazy("students:get_student")
    login_url = "main:guest"


class UpdateGroupView(LoginRequiredMixin, UpdateView):
    template_name = "teacher_update.html"
    form_class = GroupForm
    success_url = reverse_lazy("students:get_student")
    queryset = Group.objects.all()
    login_url = "main:guest"


class DeleteGroupView(LoginRequiredMixin, DeleteView):
    model = Group
    template_name = "group_delete.html"
    success_url = reverse_lazy("groups:get_group")
    login_url = "main:guest"


class TeacherGroupListView(LoginRequiredMixin, ListView):
    template_name = "teacher_group_list_view.html"
    context_object_name = "groups"
    login_url = "main:guest"

    def get_queryset(self):
        teacher = get_object_or_404(Teacher, pk=self.kwargs.get("pk"))
        queryset = teacher.group.all()
        return queryset


class GroupTeacherListView(LoginRequiredMixin, ListView):
    template_name = "group_teacher_list_view.html"
    context_object_name = "teachers"
    login_url = "main:guest"

    def get_queryset(self):
        group = get_object_or_404(Group, pk=self.kwargs.get("pk"))
        queryset = group.teacher_set.all()
        return queryset

src/groups/templates/group-create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 style="margin: 20px">Create new group</h1>
    <div>
        <form method="post" style="width: 25em; margin: auto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-success" value="Submit">Submit</button>
        </form>
    </div>
{% endblock %}

src/groups/templates/group_delete.html
{% extends "index.html" %}
{% block content %}
    <div>
        <h2>Confirm Delete</h2>
        <p>Are you sure you want to delete this group?</p>
        <form method="post" style="width: 25em; margin: auto">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete anyway</button>
            <a href="{% url 'groups:get_group' %}" class="btn btn-secondary">No</a>
        </form>
    </div>
{% endblock %}

src/groups/templates/group_get.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <h1 style="margin: 20px">Groups</h1>

    <table class="table table-dark table-striped">
        <tr style="">
            <th scope="col">Name</th>
            <th scope="col">Direction</th>
            <th scope="col">Location</th>
            <th scope="col">Price</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        {% for group in groups %}
            <tr>
                <td>{{ group.groups_name }}</td>
                <td>{{ group.direction }}</td>
                <td>{{ group.location_school }}</td>
                <td>{{ group.price }}</td>
                <td>
                    <a href="{% url "groups:update_group" group.pk %}"
                       type="button" class="btn btn-success">Edit</a>
                </td>
                <td>
                    <a href="{% url "groups:delete_group" group.pk %}"
                       type="button" class="btn btn-danger">Delete</a></td>


            </tr>
        {% endfor %}
    </table>
{% endblock %}

src/groups/templates/group_teacher_list_view.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <h1 style="margin: 20px">Teachers</h1>
    {% if teachers %}
        <table class="table table-dark table-striped">
            <tr style="">
                <th scope="col"></th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Birth date</th>
                <th scope="col">Age</th>
                <th scope="col">Date now add</th>
                <th scope="col">Current country</th>
                <th scope="col">Email</th>
            </tr>
            {% for teacher in teachers %}
                <tr>
                    {% if teacher.avatar %}
                        <td><img src="{{ teacher.avatar.url }}" alt="Avatar" style="height: 50px"></td>
                    {% else %}
                        <td>No avatar</td>
                    {% endif %}
                    <td>{{ teacher.first_name }}</td>
                    <td>{{ teacher.last_name }}</td>

                    <td>{{ teacher.birth_date }}</td>
                    {% if teacher.birth_date %}
                        <td>{{ teacher.age }}</td>
                    {% else %}
                        <td>No correct birth date</td>
                    {% endif %}
                    <td>{{ teacher.date_now_add }}</td>
                    <td>{{ teacher.current_country }}</td>
                    <td>{{ teacher.email }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        {% if request.GET.first_name or request.GET.last_name or request.GET.email %}
            <h2 style="margin-top: 10px; color: white;">No results found.</h2>
        {% else %}
            <h2 style="margin-top: 10px; color: crimson;">No results found.</h2>
        {% endif %}
    {% endif %}
{% endblock %}

src/groups/templates/teacher_group_list_view.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <h1 style="margin: 20px">Groups</h1>
    {% if groups %}
        <table class="table table-dark table-striped">
            <tr style="">
                <th scope="col">Name</th>
                <th scope="col">Direction</th>
                <th scope="col">Location</th>
                <th scope="col">Price</th>
                <th scope="col">Teaching staff</th>
            </tr>
            {% for group in groups %}
                <tr>
                    <td>{{ group.groups_name }}</td>
                    <td>{{ group.direction }}</td>
                    <td>{{ group.location_school }}</td>
                    <td>{{ group.price }}</td>

                    <td>
                        <a href="{% url "groups:group_teacher_list_view" group.pk %}"
                           type="button" class="btn btn-warning">Get group</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        {% if request.GET.first_name or request.GET.last_name or request.GET.email %}
            <h2 style="margin-top: 10px; color: white;">No results found.</h2>
        {% else %}
            <h2 style="margin-top: 10px; color: crimson;">No results found.</h2>
        {% endif %}
    {% endif %}
{% endblock %}