src/config/urls.py
from django.contrib import admin
from django.urls import path

from main.views import IndexView, PageNotFondView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path("admin/", admin.site.urls),  # admin site
    path("__debug__/", include("debug_toolbar.urls")),
    path("", IndexView.as_view(), name="index"),
    path("main/", include("main.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
handler404 = PageNotFondView.as_view()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path

from groups.views import (
    GroupTeacherListView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
    TeacherGroupListView,
    GetGroupView,
)

app_name = "groups"

urlpatterns = [
    path("", GetGroupView.as_view(), name="get_group"),
    path("group_teacher_list_view<int:pk>/", GroupTeacherListView.as_view(), name="group_teacher_list_view"),
    path("teacher_group_list/<int:pk>/", TeacherGroupListView.as_view(), name="teacher_group_list_view"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

src/main/urls.py
from django.urls import path

from main.views import (
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    GuestView,
    UserActivateView,
    ProfileView,
    UpdateUserView,
)

app_name = "main"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("guest/", GuestView.as_view(), name="guest"),
    path("activate_user/<str:uuid64>/<str:token>/", UserActivateView.as_view(), name="activate_user"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("update_user/<int:pk>/", UpdateUserView.as_view(), name="update_user"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import GetTeacherView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView

app_name = "teachers"

urlpatterns = [
    path("", GetTeacherView.as_view(), name="get_teacher"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<int:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/teachers/models.py
from django.db import models
from faker import Faker

from main.models import Person


class Teacher(Person):
    date_now_add = models.DateField(null=True, blank=True)
    current_country = models.CharField(max_length=30, null=True, blank=True)
    group = models.ManyToManyField(to="groups.Group")
    avatar = models.ImageField(upload_to="teacher/avatar_teacher/", null=True, blank=True)

    class Meta:
        verbose_name = "Teachers"
        verbose_name_plural = "All teachers"
        ordering = ("last_name",)

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_of_birth(minimum_age=18, maximum_age=60),
                date_now_add=faker.date_this_century(),
                current_country=faker.country(),
            )

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email} {self.email}"

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = [
            "first_name",
            "last_name",
            "email",
            "birth_date",
            "date_now_add",
            "current_country",
            "group",
            "avatar"
        ]

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name cannot be equal!")

        return cleaned_data

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import UpdateView, ListView, DeleteView, CreateView

from teachers.forms import TeacherForm
from teachers.models import Teacher
from django.urls import reverse_lazy


class GetTeacherView(LoginRequiredMixin, ListView):
    model = Teacher
    template_name = "teacher_get.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teacher")
    context_object_name = "teachers"
    login_url = "main:guest"

    def get_queryset(self):
        queryset = Teacher.objects.all()
        search = self.request.GET.get("searchField")
        search_fields = ["first_name", "last_name"]
        if search:
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__icontains": search})
            queryset = queryset.filter(or_filter)
        print(queryset)
        return queryset


class CreateTeacherView(LoginRequiredMixin, CreateView):
    template_name = "student-create.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teacher")
    login_url = "main:guest"


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    template_name = "teacher_update.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teacher")
    queryset = Teacher.objects.all()
    login_url = "main:guest"


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    model = Teacher
    template_name = "teacher_delete.html"
    success_url = reverse_lazy("teachers:get_teacher")
    login_url = "main:guest"

src/teachers/templates/teacher_delete.html
{% extends "index.html" %}
{% block content %}
    <div>
        <h2>Confirm Delete</h2>
        <p>Are you sure you want to delete this teacher?</p>
        <form method="post" style="width: 25em; margin: auto">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete anyway</button>
            <a href="{% url 'teachers:get_teacher' %}" class="btn btn-secondary">No</a>
        </form>
    </div>
{% endblock %}

src/teachers/templates/teacher_get.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <h1 style="margin: 20px">Teachers</h1>
    <div style="margin-bottom: 40px">
        <form method="get" style="width: 25em; margin: 30px 0 auto auto">
            <div class="input-group mb-3">
                <input type="submit" value="Search" class="btn btn-outline-secondary">
                <input type="text" class="form-control" name="searchField">
            </div>
        </form>
    </div>
    {% if teachers %}
        <table class="table table-dark table-striped">
            <tr style="">
                <th scope="col"></th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Birth date</th>
                <th scope="col">Age</th>
                <th scope="col">Date now add</th>
                <th scope="col">Current country</th>
                <th scope="col">Email</th>
                <th scope="col">Edit</th>
                <th scope="col">Look group</th>
                <th scope="col">Delete</th>
            </tr>
            {% for teacher in teachers %}
                <tr>
                    {% if teacher.avatar %}
                        <td><img src="{{ teacher.avatar.url }}" alt="Avatar" style="height: 50px"></td>
                    {% else %}
                        <td>No avatar</td>
                    {% endif %}
                    <td>{{ teacher.first_name }}</td>
                    <td>{{ teacher.last_name }}</td>

                    <td>{{ teacher.birth_date }}</td>
                    {% if teacher.birth_date %}
                        <td>{{ teacher.calculate_age }}</td>
                    {% else %}
                        <td>No correct birth date</td>
                    {% endif %}
                    <td>{{ teacher.date_now_add }}</td>
                    <td>{{ teacher.current_country }}</td>
                    <td>{{ teacher.email }}</td>
                    <td>
                        <a href="{% url "teachers:update_teacher" teacher.pk %}"
                           type="button" class="btn btn-success">Edit</a>
                    </td>
                    <td>
                        <a href="{% url 'groups:teacher_group_list_view' pk=teacher.pk %}"
                           type="button" class="btn btn-warning">Get</a>
                    </td>
                    <td>
                        <a href="{% url "teachers:delete_teacher" teacher.pk %}"
                           type="button" class="btn btn-danger">Delete</a>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        {% if request.GET.first_name or request.GET.last_name or request.GET.email %}
            <h2 style="margin-top: 10px; color: white;">No results found.</h2>
        {% else %}
            <h2 style="margin-top: 10px; color: crimson;">No results found.</h2>
        {% endif %}
    {% endif %}
{% endblock %}

src/teachers/templates/teacher_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <form method="post" style="width: 25em; margin: auto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-success" value="Update">Update</button>
        </form>
    </div>
{% endblock %}