src/config/urls.py
from django.contrib import admin
from django.urls import path

from main.views import IndexView, PageNotFondView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path("admin/", admin.site.urls),  # admin site
    path("__debug__/", include("debug_toolbar.urls")),
    path("", IndexView.as_view(), name="index"),
    path("main/", include("main.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
handler404 = PageNotFondView.as_view()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from main.views import (
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    GuestView,
    UserActivateView,
    ProfileView,
    UpdateUserView,
)

app_name = "main"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("guest/", GuestView.as_view(), name="guest"),
    path("activate_user/<str:uuid64>/<str:token>/", UserActivateView.as_view(), name="activate_user"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("update_user/<int:pk>/", UpdateUserView.as_view(), name="update_user"),
]

src/students/urls.py
from django.urls import path
from students.views import CreateStudentView, UpdateStudentView, GetStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path("", GetStudentView.as_view(), name="get_student"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:uuid>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/students/models.py
import random
from uuid import uuid4

from django.db import models
from faker import Faker

from groups.models import Group
from main.models import Person


class Student(Person):
    uuid = models.UUIDField(default=uuid4, primary_key=True, unique=True, editable=False, db_index=True)
    group = models.ForeignKey(to="groups.Group", on_delete=models.CASCADE)
    grade = models.PositiveSmallIntegerField(null=True, blank=True)
    avatar = models.ImageField(upload_to="student/avatar_student/", null=True, blank=True)
    resume = models.FileField(upload_to="student/resume_student/", null=True, blank=True)

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "All students"
        ordering = ("last_name",)

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_of_birth(minimum_age=18, maximum_age=60),
                group=Group.objects.get(id=random.randint(1, 5)),
            )

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email}"

src/students/forms.py
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ["first_name", "last_name", "email", "group", "avatar", "resume"]

src/students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from students.forms import StudentForm
from students.models import Student
from django.urls import reverse_lazy


class GetStudentView(LoginRequiredMixin, ListView):
    model = Student
    template_name = "student_get.html"
    form_class = StudentForm
    pk_url_kwarg = "uuid"
    success_url = reverse_lazy("students:get_student")
    context_object_name = "students"
    login_url = "main:guest"

    def get_queryset(self):
        queryset = Student.objects.all()
        search = self.request.GET.get("searchField")
        search_fields = ["first_name", "last_name", "email"]
        if search:
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__icontains": search})
            queryset = queryset.filter(or_filter)
        return queryset


class CreateStudentView(LoginRequiredMixin, CreateView):
    template_name = "student-create.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_student")
    login_url = "main:guest"


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    template_name = "student_update.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_student")
    queryset = Student.objects.all()
    pk_url_kwarg = "uuid"
    login_url = "main:guest"


class DeleteStudentView(LoginRequiredMixin, DeleteView):
    model = Student
    template_name = "student_delete.html"
    success_url = reverse_lazy("students:get_student")
    pk_url_kwarg = "uuid"
    login_url = "main:guest"

src/students/templates/student-create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 style="margin: 20px">Create new student</h1>
    <div>
        <form method="post" style="width: 25em; margin: auto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-success" value="Submit">Submit</button>
        </form>
    </div>
{% endblock %}

src/students/templates/student_delete.html
{% extends "index.html" %}
{% block content %}
    <div>
        <h2>Confirm Delete</h2>
        <p>Are you sure you want to delete this student?</p>
        <form method="post" style="width: 25em; margin: auto">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete anyway</button>
            <a href="{% url 'students:get_student' %}" class="btn btn-secondary">No</a>
        </form>
    </div>
{% endblock %}

src/students/templates/student_get.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <h1 style="margin: 20px">Students</h1>
    <div style="margin-bottom: 40px">
        <form method="get" style="width: 25em; margin: 30px 0 auto auto">
            <div class="input-group mb-3">
                <input type="submit" value="Search" class="btn btn-outline-secondary">
                <input type="text" class="form-control" name="searchField">
            </div>
        </form>
    </div>
    {% if students %}
        <table class="table table-dark table-striped">
            <tr style="">
                <th scope="col"></th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Email</th>
                <th scope="col">Birth date</th>
                <th scope="col">Age</th>
                <th scope="col">Grade</th>
                <th scope="col">Group</th>
                <th scope="col">Edit</th>
                <th scope="col">Resume</th>
                <th scope="col">Delete</th>
            </tr>
            {% for student in students %}
                <tr>
                    {% if student.avatar %}
                        <td><img src="{{ student.avatar.url }}" alt="Avatar" style="height: 50px"></td>
                    {% else %}
                        <td>No avatar</td>
                    {% endif %}

                    <td>{{ student.first_name }}</td>
                    <td>{{ student.last_name }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.birth_date }}</td>
                    {% if student.birth_date %}
                        <td>{{ student.calculate_age }}</td>
                    {% else %}
                        <td>No correct birth date</td>
                    {% endif %}

                    {% if student.grade %}
                        <td>{{ student.grade }}</td>

                    {% else %}
                        <td>No information</td>
                    {% endif %}
                    {% if student.group %}
                        <td>{{ student.group }}</td>

                    {% else %}
                        <td>No information</td>
                    {% endif %}
                    <td>
                        <a href="{% url "students:update_student" student.pk %}"
                           type="button" class="btn btn-success">Edit</a>
                    </td>
                    {% if student.resume %}
                        {% if student.resume.url|slice:"-4:" == ".pdf" %}
                            <td><a href="{{ student.resume.url }}" target="_blank" type="button"
                                   class="btn btn-info">Open PDF</a></td>
                        {% else %}
                            <td><a href="{{ student.resume.url }}" download type="button"
                                   class="btn btn-info">Download</a></td>
                        {% endif %}
                    {% else %}
                        <td>No resume</td>
                    {% endif %}
                    <td>
                        <a href="{% url "students:delete_student" student.pk %}"
                           type="button" class="btn btn-danger">Delete</a>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        {% if request.GET.first_name or request.GET.last_name or request.GET.email %}
            <h2 style="margin-top: 10px; color: white;">No results found.</h2>
        {% else %}
            <h2 style="margin-top: 10px; color: crimson;">No results found.</h2>
        {% endif %}
    {% endif %}
{% endblock %}

src/students/templates/student_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <form method="post" style="width: 25em; margin: auto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-success" value="Update">Update</button>
        </form>
    </div>
{% endblock %}