src/config/urls.py
from django.contrib import admin
from django.urls import path

from main.views import IndexView, PageNotFondView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path("admin/", admin.site.urls),  # admin site
    path("__debug__/", include("debug_toolbar.urls")),
    path("", IndexView.as_view(), name="index"),
    path("main/", include("main.urls")),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
handler404 = PageNotFondView.as_view()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path

from groups.views import (
    GroupTeacherListView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
    TeacherGroupListView,
    GetGroupView,
)

app_name = "groups"

urlpatterns = [
    path("", GetGroupView.as_view(), name="get_group"),
    path("group_teacher_list_view<int:pk>/", GroupTeacherListView.as_view(), name="group_teacher_list_view"),
    path("teacher_group_list/<int:pk>/", TeacherGroupListView.as_view(), name="teacher_group_list_view"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
]

src/main/urls.py
from django.urls import path

from main.views import (
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    GuestView,
    UserActivateView,
    ProfileView,
    UpdateUserView,
)

app_name = "main"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
    path("guest/", GuestView.as_view(), name="guest"),
    path("activate_user/<str:uuid64>/<str:token>/", UserActivateView.as_view(), name="activate_user"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("update_user/<int:pk>/", UpdateUserView.as_view(), name="update_user"),
]

src/students/urls.py
from django.urls import path
from students.views import CreateStudentView, UpdateStudentView, GetStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path("", GetStudentView.as_view(), name="get_student"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:uuid>/", DeleteStudentView.as_view(), name="delete_student"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import GetTeacherView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView

app_name = "teachers"

urlpatterns = [
    path("", GetTeacherView.as_view(), name="get_teacher"),
    path("create/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update/<int:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/main/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.core.validators import MinLengthValidator
from django.db import models
import datetime
from django.utils import timezone

from main.managers import CustomerManager
from main.utils.validators import first_name_validator
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class Customer(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True, error_messages="A user with that email already exists.")
    avatar = models.ImageField(upload_to="user/avatar_user", null=True, blank=True)
    phone_number = PhoneNumberField(blank=True, null=True, help_text="+1234567890")
    CHOICES = (
        ("STUDENT", "Student"),
        ("TEACHER", "Teacher"),
        ("MENTOR", "Mentor"),
    )
    user_type = models.CharField(
        max_length=10,
        choices=CHOICES,
    )
    company = models.CharField(blank=True, null=True, max_length=100)
    higher_education = models.BooleanField(default=False, help_text="Check the box if available")
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. " "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = CustomerManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("Customer")
        verbose_name_plural = _("All Customers")
        abstract = False
        ordering = ("last_name",)

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email} {self.email}"

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def get_period_of_registration(self):
        return f"Time on site: {timezone.now() - self.date_joined}"


class Person(models.Model):
    first_name = models.CharField(
        max_length=120,
        null=True,
        blank=True,
        validators=[MinLengthValidator(2, message="incorrect"), first_name_validator],
    )
    last_name = models.CharField(max_length=120, null=True, blank=True)
    email = models.EmailField(max_length=150, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    class Meta:
        abstract = True

    def calculate_age(self):
        if self.birth_date:
            today = datetime.date.today()
            age = today.year - self.birth_date.year
            if today.month < self.birth_date.month or (
                today.month == self.birth_date.month and today.day < self.birth_date.day
            ):
                age -= 1
            return age
        return None

src/main/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from main.models import Customer


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = Customer
        fields = ["email", "password1", "password2", "first_name", "last_name"]


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = Customer
        fields = [
            "email",
            "first_name",
            "last_name",
            "avatar",
            "phone_number",
            "user_type",
            "company",
            "higher_education",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop("password")

src/main/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views.generic import CreateView, RedirectView, DetailView, UpdateView
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from main.forms import UserRegistrationForm, UserUpdateForm
from main.models import Customer
from main.services.emails import send_registration_email
from main.utils.token_generator import TokenGenerator


class IndexView(TemplateView):
    template_name = "index.html"
    http_method_names = ["get"]


class UserLoginView(LoginView):
    template_name = "login.html"


class UserLogoutView(LogoutView):
    ...


class UserRegistrationView(CreateView):
    template_name = "user_create.html"
    form_class = UserRegistrationForm
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        send_registration_email(request=self.request, user_instance=user)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UserActivateView(RedirectView):
    url = reverse_lazy("index")
    template_name = "emails/wrong_data.html"

    def get(self, request, uuid64, token, *args, **kwargs):
        try:
            pk = force_str(urlsafe_base64_decode(uuid64))
            current_user = get_user_model().objects.get(pk=pk)
        except (get_user_model().DoesNotExist, TypeError, ValueError):
            return render(request, self.template_name)

        if current_user and TokenGenerator().check_token(current_user, token):
            current_user.is_active = True
            current_user.save()
            login(request, current_user, backend="django.contrib.auth.backends.ModelBackend")

            return super().get(request, *args, **kwargs)
        return render(request, self.template_name)


class PageNotFondView(TemplateView):
    template_name = "404.html"
    http_method_names = ["get"]


class GuestView(TemplateView):
    template_name = "guest_view.html"
    http_method_names = ["get"]


class ProfileView(DetailView):
    model = Customer
    template_name = "profile.html"
    context_object_name = "user_info"
    queryset = Customer.objects.all()


class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = Customer
    template_name = "user_update.html"
    login_url = "main:guest"
    form_class = UserUpdateForm

    def get_success_url(self):
        return reverse_lazy("main:profile", kwargs={"pk": self.object.pk})

src/main/templates/guest_view.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <h1>You are not authorized to perform these actions, please register or log in to your account</h1>
    </div>
{% endblock %}

src/main/templates/index.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Cover Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/cover/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!-- Bootstrap core CSS -->
    <link href={% static "css/cover.css" %} rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        #my-link {
            color: white;
        }

        #my-link:hover {
            color: #6c757d;
        }


    </style>


    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <a href="{% url 'index' %}" id="my-link">
                <h3 class="float-md-start mb-0">
                    My LMS
                </h3>
            </a>


            <nav class="nav nav-masthead justify-content-center float-md-end">
                {% if user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="{% url "index" %}"
                       style="margin-right: 1em">Home</a>


                    <div class="flex-shrink-0 dropdown" style="margin-right: 1em;">
                        <a href="#" class="nav-link d-block link-dark text-decoration-none dropdown-toggle"
                           id="dropdownUser2"
                           data-bs-toggle="dropdown" aria-expanded="false" aria-current="page">Student
                        </a>
                        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                            <li><a class="dropdown-item" href="{% url 'students:get_student' %}">Students</a></li>
                            <li><a class="dropdown-item" href="{% url 'students:create_student' %}">Create new
                                student</a>
                            </li>
                        </ul>
                    </div>

                    <div class="flex-shrink-0 dropdown" style="margin-right: 1em;">
                        <a href="#" class="nav-link d-block link-dark text-decoration-none dropdown-toggle"
                           id="dropdownUser2"
                           data-bs-toggle="dropdown" aria-expanded="false" aria-current="page">Teacher
                        </a>
                        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                            <li><a class="dropdown-item" href="{% url "teachers:get_teacher" %}">Teachers</a></li>
                            <li><a class="dropdown-item" href="{% url "teachers:create_teacher" %}">Create new
                                teacher</a>
                            </li>
                        </ul>
                    </div>


                    <div class="flex-shrink-0 dropdown" style="margin-right: 1em;">
                        <a href="#" class="nav-link d-block link-dark text-decoration-none dropdown-toggle"
                           id="dropdownUser2"
                           data-bs-toggle="dropdown" aria-expanded="false" aria-current="page">Group
                        </a>
                        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                            <li><a class="dropdown-item" href="{% url "groups:get_group" %}">Groups</a></li>
                            <li><a class="dropdown-item" href="{% url "groups:create_group" %}">Create new Group</a>
                            </li>
                        </ul>
                    </div>
                {% else %}
                {% endif %}

                <div class="flex-shrink-0 dropdown">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {% if user.is_authenticated and user.avatar %}
                            <img src="{{ user.avatar }}" alt="mdo" width="32" height="32"
                                 class="rounded-circle">
                        {% else %}
                            <img src="{% static 'images/user_logo.png' %}" alt="mdo" width="32" height="32"
                                 class="rounded-circle">
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                        {% if user.is_authenticated %}
                            <li>
                                <h6 class="dropdown-item">{{ user.first_name|title }} {{ user.last_name|title }}</h6>
                            </li>
                            <li>
                                <hr class="dropdown-devider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'main:profile' user.pk %}">Profile</a></li>
                            <li><a class="dropdown-item" href="#">Change password</a></li>
                            <li><a class="dropdown-item" href="#">Settings</a></li>
                            <li>
                                <hr class="dropdown-devider">
                            </li>
                            <li><a class="dropdown-item" href="{% url "main:logout" %}">Log out</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url "main:login" %}">Log in</a></li>
                            <li><a class="dropdown-item" href="{% url "main:registration" %}">Registration</a></li>
                            <li><a class="dropdown-item" href="#">Reset password</a></li>
                            <li>
                                <hr class="dropdown-devider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'social:begin' 'google-oauth2' %}">Registration
                                with Google</a></li>
                            <hr class=" dropdown-devider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'social:begin' 'github' %}">Registration with
                                GitHub</a>
                            </li>
                            <hr class=" dropdown-devider">
                            <li><a class="dropdown-item" href="{% url 'social:begin' 'gitlab' %}">Registration with
                                Gitlab</a>
                            </li>
                            <hr class=" dropdown-devider">
                            <li><a class="dropdown-item" href="{% url 'social:begin' 'linkedin-oauth2' %}">Registration with
                                LinkedLn</a>
                            </li>
                            </li>
                        {% endif %}
                    </ul>
                </div>

            </nav>
        </div>
    </header>

    <main class="px-3">
        {% block content %}
            <img src="https://assets.ithillel.ua/Hillel-Logo-Organization.png" alt="" style="width: 50%">
        {% endblock %}
    </main>

    <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>


</body>
</html>

src/main/templates/login.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <form method="post" style="width: 25em; margin: auto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-success" value="Login">Login</button>
        </form>
    </div>
{% endblock %}

src/main/templates/profile.html
{% extends "index.html" %}
{% load static %}
{% block content %}

    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>First Name:</strong> {{ user.first_name }}</p>
    <p><strong>Last Name:</strong> {{ user.last_name }}</p>
    <p><strong>Avatar:</strong>
        {% if user.avatar %}
            <img src="{{ user.avatar.url }}" alt="Avatar" style="height:50px; border-radius: 50px">
        {% else %}
            <td>No avatar</td>
        {% endif %}</p>
    <p><strong>Phone Number:</strong> {{ user.phone_number }}</p>
    <p><strong>User Type:</strong> {{ user.get_user_type_display }}</p>
    <p><strong>Location:</strong> {{ user.location }}</p>
    <p><strong>Company:</strong> {{ user.company }}</p>
    <p><strong>Higher Education:</strong> {{ user.higher_education }}</p>

    <a href="{% url "main:update_user" user.pk %}"
       type="button" class="btn btn-success">Edit</a>

{% endblock %}

src/main/templates/user_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <form method="post" style="width: 25em; margin: auto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-success" value="Registration">Registration</button>
        </form>
    </div>
{% endblock %}

src/main/templates/user_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <form method="post" style="width: 25em; margin: auto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success" style="margin-top: 20px">Update</button>
        </form>
    </div>
{% endblock %}